### ISSUE TITLE
Fail to flash - error line 425

### ISSUE THREAD

**Issue by G1RGG** [wh6av/md380-radio#1]
----- cut from Putty window---------------------------------------------------------------------
Proceeding to update radio firmware.
./md380-update: line 425: cd: /home/pi/md380-radio/md380tools: No such file or directory
make: **\* No rule to make target 'flash'.  Stop. ---------------------------------------------------------------------------------------------------
Radio Retevis R3.  (radio and usb lead work ok for flashing and programing in windiws 7)
Raspberry pi 2. with 2016-05-27-raspbian-jessie.img from raspberrypi.org
I used "SETUP PROCEDURE 1"
Then I did steps 1,2,3,4,5 in your script.

Phil G1RGG

**Comment by G1RGG** [comment]
Ok Just tred again and looks like its all woking.

**Comment by wh6av** [comment]
Glad you got it working!

**Comment by G1RGG** [comment]
Hi.Dont know what i did but works fine now 

Thanks for youe work.
Phil G1RGG. 

```
On Sunday, 11 September 2016, 17:11, WH6AV <notifications@github.com> wrote:
```

 Glad you got it working! —
